
/**
 * Ref: http://www.dayexie.com/detail2034943.html
 */
--PRIOR:  
SELECT DISTINCT SREQUIRED.requires
FROM SREQUIRED
CONNECT BY PRIOR SREQUIRED.requires = sname;

--LEVEL:
SELECT DISTINCT SREQUIRED.requires, LEVELFROM SREQUIRED
CONNECT BY PRIOR SREQUIRED.requires = SREQUIRED.sname;


--START WITH:
SELECT DISTINCT SREQUIRED.requires, LEVELFROM SREQUIRED
START WITH SREQUIRED.sname = 'CORBA programming'
CONNECT BY PRIOR SREQUIRED.requires = SREQUIRED.sname;


--SIBLINGS BY:   
SELECT DISTINCT SREQUIRED.requires, SREQUIRED.slevel,LEVELFROM SREQUIRED
START WITH SREQUIRED.sname = 'CORBA programming'
CONNECT BY PRIOR SREQUIRED.requires = SREQUIRED.sname
ORDER SIBLINGS BY SREQUIRED.slevel;


--NOCYCLE:
SELECT DISTINCT SREQUIRED.requires, SREQUIRED.slevel,LEVELFROM SREQUIRED
START WITH SREQUIRED.sname = 'CORBA programming'
CONNECT BY NOCYCLE
PRIOR SREQUIRED.requires = SREQUIRED.sname;


--CONNECT_BY_ISCYCLE:    
SELECT DISTINCT SREQUIRED.requires, SREQUIRED.slevel,
LEVEL, CONNECT_BY_ISCYCLE
FROM SREQUIRED
START WITH SREQUIRED.sname = 'CORBA programming'CONNECT BY NOCYCLE
PRIOR SREQUIRED.requires = SREQUIRED.sname;


--SYS_CONNECT_BY_PATH:   
SELECT DISTINCT SREQUIRED.requires, SREQUIRED.slevel,
LEVEL, SYS_CONNECT_BY_PATH(SREQUIRED.requires,'>')
FROM SREQUIRED
START WITH SREQUIRED.sname = 'CORBA programming'
CONNECT BY PRIOR SREQUIRED.requires = SREQUIRED.sname;


--CONNECT_BY_ROOT:
SELECT DISTINCT SREQUIRED.requires, SREQUIRED.slevel,CONNECT_BY_ROOT(SREQUIRED.requires), LEVELFROM SREQUIRED
START WITH SREQUIRED.sname = 'CORBA programming'
CONNECT BY PRIOR SREQUIRED.requires = SREQUIRED.sname;


--CUBE:
SELECT R_NAME, N_NAME, COUNT(*)
FROM REGION JOIN NATION
ON R_REGIONKEY = N_REGIONKEY
GROUP BY CUBE(R_NAME, N_NAME);


--GROUPING SET:
SELECT R_NAME, N_NAME, COUNT(*)
FROM REGION JOIN NATION
     ON R_REGIONKEY = N_REGIONKEY
GROUP BY GROUPING SETS((R_NAME), (N_NAME), NULL);

