/**
 * Merge
 */

--Insert, where(optional)
MERGE INTO ALL_SUPPLIERS
USING SUPPLIER SON (ALL_SUPPLIERS.S_SUPPKEY = S.S_SUPPKEY)
WHEN NOT MATCHED THENINSERT VALUES(
	S.S_SUPPKEY, S.S_NAME, S.S_ADDRESS,
	S.S_NATIONKEY,S.S_PHONE, S.S_ACCTBAL,S.S_COMMENT)
	
--Delete
MERGE INTO ALL_SUPPLIERS
USING SUPPLIER SON (ALL_SUPPLIERS.S_SUPPKEY = S.S_SUPPKEY)
WHEN MATCHED THENUPDATE SET ALL_SUPPLIERS.S_ADDRESS = S.S_ADDRESS
DELETE WHERE S.S_NAME = 'James Bond'
